export const BASE_URL = ''
export const TICKETS_URL = '/api/tickets'
export const USERS_URL = '/api/users'
export const PAYPAL_URL = '/api/config/paypal'
export const UPLOAD_URL = '/api/uploads'
export const CLIENTS_URL = '/api/clients'